### ISSUE TITLE
Automated "Bad news" emails

### ISSUE THREAD

**Issue by idengager** [LunarLogic/rails-girls-submissions#129]
Just like we can send acceptance emails with a click of a button (or, like, three), it would be great to send a note to the people that didn't make the list. Not sure if it should be done as a separate step (probably not), but it needs to be documented as such, so that it's clear to the people clicking the button(s).

- [ ] Give more priority to background jobs that deliver invitations and lower priority for rejections.

**Comment by ravicious** [comment]
As Basia said on Slack, "we have been sending the rejection email via mailchimp, because we wrote it there 7 years ago, but it definitely be a good idea to move it to the app".

I think we could send this rejection email once, right when we send the first batch of invitation emails.

**Comment by ravicious** [comment]
Solution to re-evaluate in the nearest future: when pulling submissions to invite (which depends on a limit), do an offset in order to pull the rest of submissions, send them a bad news email and flip a flag which says that they got the email. When pulling the rest of submissions, we need to only fetch those which have that flag set to null so that we only send the bad news email once.

**Comment by ravicious** [comment]
Done in fa81ccff6c1, now we just need to make adjustments to the bad news email (if we have any).

![bad news email](https://user-images.githubusercontent.com/27113/57573950-947d4280-7430-11e9-99ee-a662a5043c6c.png)
